### ISSUE TITLE
Közterület neve és jellene nélküli elemek kezelése

### ISSUE THREAD

**Issue by KAMI911** [bkil/osm-grammars#2]
Bemenő adatok:

        "lat":'46.53155',
        "lng": '20.883113',
        "cim": '5662 Csanádapáca',

Ebbőél ez az ast lesz:

addr
->  postcode
    |   5
    |   6
    |   6
    |   2
->  wStreet
    |   C
    |   s
    |   a
    |   n
    |   á
    |   d
    |   a
    |   p
    |   á
    |   c
    |   a

Miért nem település lesz Csanádapáca névből? Ez nem egy bug?

**Comment by bkil** [comment]
Fixed https://github.com/bkil/osm-grammars/commit/20143853fd49dd1756f658943f839c0636712437
