### ISSUE TITLE
Parser error hiba a címeknél

### ISSUE THREAD

**Issue by KAMI911** [bkil/osm-grammars#4]
Kezdem ráengedni szélesebb körre az elemződet, és az alábbi címek mind ParserError-ra futnak, azaz nem sikerül a szövegek értelmezése:
1214 Budapest II.Rákóczi F.út 195-197.
9737 Bük, 0131/3 hrsz.
9735 Csepreg, 020/38 hrsz. Szakony felé
6525 Hercegszántó, 1216/2 hrsz.
7523 Kaposfő, 643/5 hrsz.
2462 Martonvásár, Bajcsy-Zs.E.u.31.
2142 Nagytarcsa 0135/50 hrsz.
8683 Somogytúr, HRSZ: 09/4.
6763 Szatymaz, IV. kerület 130. Hrsz.: 0261/4.
7130 Tolna, HRSZ.: 077/4.
8798 Zalabér, 03155/2 hrsz.

Tudnád ezeket javítani?

AttributeError: 'ParseError' object has no attribute 'children'

**Comment by bkil** [comment]
All fixed except one in https://github.com/bkil/osm-grammars/commit/a4b0c67d68ad591798decfdba328f9530da98d7b

Please open a separate and properly named issue that deals with extra comments at the end where you gather all exemplars occurring in the wild.
